spring:
  profiles:
    active: dev
  application:
    name: MqttClient
  main:
    web-application-type: none
management:
  security:
    enabled: false
security:
  basic:
    enabled: false
grpc:
  service:
    name: GRPCSERVERSERVICE

