mqtt:
  server:
    ip: tcp://localhost
    port: 1883

spring:
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
