spring:
  profiles:
    active: dev
  application:
    name: MqttClient
  main:
    web-application-type: none

  kafka:
    consumer:
      group-id: iot-mqtt-client-service
      topics: "CREATE_DEVICE_MEASUREMENT,UPDATE_DEVICE_MEASUREMENT,DELETE_DEVICE_MEASUREMENT"

management:
  security:
    enabled: false
security:
  basic:
    enabled: false

mqtt:
  qos: 1

grpc:
  service:
    name: GRPCSERVERSERVICE

