version: '3'
services:
  postgres:
    image: postgres
    hostname: MicroservicesApp-postgres
    container_name: MicroservicesApp-postgres
    network_mode: bridge
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MicroservicesAppDB

  user_service:
    container_name: user_service
    build: ./UserService
    ports:
      - "8081:8081"

  iot_device_service:
    container_name: iot_device_service
    build: ./IotDeviceService
    ports:
      - "8082:8082"
