version: "3.8"

services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    restart: always
    ports:
      - "1883:1883" # default MQTT port
      - "9001:9001" # default MQTT port for websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
    command: [ "sh", "-c", "cp /mosquitto/config/mosquitto_custom.conf /mosquitto/config/mosquitto.conf && exec mosquitto -c /mosquitto/config/mosquitto.conf" ]
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: always
    depends_on:
      - mqtt5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network

  postgres_db:
    image: postgres
    container_name: MicroservicesApp-postgres
    restart: always
    depends_on:
      - mqtt5
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  eurekaserver:
    container_name: eurekaserver
    restart: always
    depends_on:
      - mqtt5
      - kafka
      - postgres_db
    ports:
      - "8761:8761"
    build: ./EurekaServer
    networks:
      - my-network

  user-service:
    container_name: user-service
    restart: always
    depends_on:
      - eurekaserver
    ports:
      - "8008:8008"
    build: ./UserService
    networks:
      - my-network

  api-gateway-service:
    container_name: api-gateway-service
    restart: always
    depends_on:
      - real_time_data_service
    ports:
      - "8080:8080"
    build: ./ApiGatewayService
    networks:
      - my-network

  
  grpcserverservice:
    container_name: grpcserverservice
    restart: always
    depends_on:
      - eurekaserver
      - user-service
    ports:
      - "9090:9090"
    build: ./GrpcServerService
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - eurekaserver
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my-network

  iotdeviceservice:
    container_name: iotdeviceservice
    build: ./IotDeviceService
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - eurekaserver
    networks:
      - my-network

  mqtt_client_service:
    container_name: mqtt_client_service
    restart: always
    depends_on:
      - eurekaserver
      - grpcserverservice
    build: ./MqttClient
    networks:
      - my-network

  real_time_data_service:
    container_name: real_time_service
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - eurekaserver
      - grpcserverservice
      - mqtt_client_service
    build: ./RealTimeDataService
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data:
  config:
  data:
  log: