version: "3.8"

services:

  postgres:
    image: postgres
    container_name: MicroservicesApp-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MicroservicesAppDB
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  user_service:
    container_name: user_service
    build: ./UserService
    ports:
      - "8081:8081"

  iot_device_service:
    container_name: iot_device_service
    build: ./IotDeviceService
    ports:
      - "8082:8082"

volumes:
  local_pgdata:
  pgadmin-data: