version: "3.8"

services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets

  postgres_db:
    image: postgres
    container_name: MicroservicesApp-postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres_db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  user_service:
    container_name: user_service
    build: ./UserService
    ports:
      - "8000:8000"

  iot_device_service:
    container_name: iot_device_service
    build: ./IotDeviceService
    ports:
      - "8001:8001"

volumes:
  local_pgdata:
  pgadmin-data: