spring:
  profiles:
    active: dev
  application:
    name: RealTimeDataService
  kafka:
    consumer:
      group-id: iot-info-service
      topics: "CREATE_DEVICE_MEASUREMENT,UPDATE_DEVICE_MEASUREMENT,DELETE_DEVICE_MEASUREMENT"

server:
  port: 8005
management:
  security:
    enabled: false
security:
  basic:
    enabled: false

grpc:
  service:
    name: GRPCSERVERSERVICE

mqtt:
  qos: 1