spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: iot-info-service
      topics: "CREATE_DEVICE_MEASUREMENT,UPDATE_DEVICE_MEASUREMENT,DELETE_DEVICE_MEASUREMENT"
grpc:
  server:
    address: 127.0.0.1
    port: 9090
mqtt:
  server:
    ip: tcp://localhost
    port: 1883
  qos: 1