spring:
  profiles:
    active: dev
  application:
    name: stream-service
  kafka:
    consumer:
      group-id: iot-info-service
      topics: "CREATE_DEVICE_MEASUREMENT,UPDATE_DEVICE_MEASUREMENT,DELETE_DEVICE_MEASUREMENT"

server:
  port: 8005

management:
  endpoints:
    web:
      exposure:
        include: "health"

  security:
    enabled: false

security:
  basic:
    enabled: false

grpc:
  service:
    name: grpc-server-service

mqtt:
  qos: 1