spring:
  profiles:
    active: dev
  application:
    name: ApiGatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

services:
  userService:
    name: USERSERVICE
