spring:
  profiles:
    active: dev
  application:
    name: ApiGatewayService
services:
  grpcService:
    name: GRPCSERVERSERVICE
  iotDeviceService:
    name: IOTDEVICESERVICE
  RealTimeDataService:
    name: REALTIMEDATASERVICE

