spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/microservices
    username: admin
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

