spring:

  profiles:
    active: dev

  application:
    name: grpc-server-service

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    web-application-type: none

server:
  port: 9090

grpc:
  server:
    port: 9090
